[project]
name = "mytools-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "nguyendangviet12022004", email = "viet.ngdang.dev@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "typer>=0.27.2",
]

[project.scripts]
mytools-project = "mytools_project:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
